insert into public.sentences (text, notebook_id) values ('Success is becoming in middle adulthood what you dreamed to be in late childhood. The rest comes from loss of control.', 26);
insert into public.sentences (text, notebook_id) values ('The opposite of success isn''t failure; it is namedropping.', 26);
insert into public.sentences (text, notebook_id) values ('Modernity needs to understand that being rich and becoming rich are not mathematically, personally, socially, and ethically the same thing.', 26);
insert into public.sentences (text, notebook_id) values ('You don''t become completely free by just avoiding to be a slave; you also need to avoid becoming a master.', 26);
insert into public.sentences (text, notebook_id) values ('Fortune punishes the greedy by making him poor and the very greedy by making him rich.', 26);
insert into public.sentences (text, notebook_id) values ('Quite revealing of human preferences that more suicides come from shame or loss of financial and social status than medical diagnoses.', 26);
insert into public.sentences (text, notebook_id) values ('"Wealthy" is meaningless and has no robust absolute measure; use intead the subtractive measure "unwealth," that is, the difference, at any point in time, between what you have and what you would like to have.', 26);
insert into public.sentences (text, notebook_id) values ('Older people are most beautiful when they have what is lacking in the young: poise, erudition, wisdom, phronesis, and this postheroic absence of agitation.', 26);
insert into public.sentences (text, notebook_id) values ('I went to a happiness conference; researchers looked very unhappy.', 26);
insert into public.sentences (text, notebook_id) values ('What fools call "wasting time" is most often the best investment.', 26);
insert into public.sentences (text, notebook_id) values ('Decline starts with the replacement of dreams with memories and ends with the replacement of memories with other memories.', 26);
insert into public.sentences (text, notebook_id) values ('You want to avoid being disliked without being envied or admired.', 26);
insert into public.sentences (text, notebook_id) values ('Read nothing from the past one hundred years; eat no fruits from the past one thousand years; drink nothing from the past four thousand years (just wine and water); but talk to no ordinary man over forty. A man without a heroic bent starts dying at the age of thirty.', 26);
insert into public.sentences (text, notebook_id) values ('Some pursuits are much duller from the inside. Even piracy, they say.', 26);
insert into public.sentences (text, notebook_id) values ('Karl Marx, a visionary, figured out that you can control a slave much better by convincing him he is an employee.', 26);
insert into public.sentences (text, notebook_id) values ('Catholic countries had more serial monogamy than today, but without the need for divorcelife expectancy was short; marriage duration was much, much shorter.', 26);
insert into public.sentences (text, notebook_id) values ('The fastest way to become rich is to socialize with the poor; the fastest way to become poor is to socialize with the rich.', 26);
insert into public.sentences (text, notebook_id) values ('You will be civilized on the day you can spend a long period doing nothing, learning nothing, and improving nothing, without feeling the slightest amount of guilt.', 26);
insert into public.sentences (text, notebook_id) values ('Someone who says "I am busy" is either declaring incompetence (and lack of control of his life) or trying to get rid of you.', 26);
insert into public.sentences (text, notebook_id) values ('The difference between slaves in Roman and Ottoman days and today''s employees is that slaves did not need to flatter their boss.', 26);
insert into public.sentences (text, notebook_id) values ('You are rich if and only if money you refuse tastes better than money you accept.', 26);
insert into public.sentences (text, notebook_id) values ('For most, success is the harmful passage from the camp of the hating to the camp of the hated.', 26);
insert into public.sentences (text, notebook_id) values ('To see if you like where you are, without the chains of dependence, check if you are as happy returning as you were leaving.', 26);
insert into public.sentences (text, notebook_id) values ('The difference between love and happiness is that those who talk about love tend to be in love, but those who talk about happiness tend to be not happy.', 26);
insert into public.sentences (text, notebook_id) values ('Modernity: we created youth without heroism, age without wisdom, and life without grandeur.', 26);
insert into public.sentences (text, notebook_id) values ('You can tell how uninteresting a person is by asking him whom he finds interesting.', 26);
insert into public.sentences (text, notebook_id) values ('The Web is an unhealthy place for someone hungry for attention.', 26);
insert into public.sentences (text, notebook_id) values ('I wonder if anyone ever measured the time it takes, at a party, before a mildly successful stranger who went to Harvard makes others aware of it.', 26);
insert into public.sentences (text, notebook_id) values ('People focus on role models; it is more effective to find antimodelspeople you don''t want to resemble when you grow up.', 26);
insert into public.sentences (text, notebook_id) values ('It is a good practice to always apologize, except when you have done something wrong.', 26);
insert into public.sentences (text, notebook_id) values ('Preoccupation with efficacy is the main obstacle to a poetic, noble, elegant, robust, and heroic life.', 26);
insert into public.sentences (text, notebook_id) values ('Some, like most bankers, are so unfit for success that they look like dwarves dressed in giants'' clothes.', 26);
insert into public.sentences (text, notebook_id) values ('Don''t complain too loud about wrongs done you; you may give ideas to your less imaginative enemies.', 26);
insert into public.sentences (text, notebook_id) values ('Most feed their obsessions by trying to get rid of them.', 26);
insert into public.sentences (text, notebook_id) values ('It is as difficult to change someone''s opinions as it is to change his tastes.', 26);
insert into public.sentences (text, notebook_id) values ('I have the fondest memories of time spent in places called ugly, the most boring ones of places called scenic.', 26);
insert into public.sentences (text, notebook_id) values ('Fitness is certainly the sign of strength, but outside of natural stimuli the drive to acquire =tness can signal some deep incurable weakness.', 26);
insert into public.sentences (text, notebook_id) values ('Charm is the ability to insult people without offending them; nerdiness the reverse.', 26);
insert into public.sentences (text, notebook_id) values ('Those who do not think that employment is systemic slavery are either blind or employed.', 26);
insert into public.sentences (text, notebook_id) values ('They are born, then put in a box; they go home to live in a box; they study by ticking boxes; they go to what is called "work" in a box, where they sit in their cubicle box; they drive to the grocery store in a box to buy food in a box; they go to the gym in a box to sit in a box; they talk about thinking "outside the box"; and when they die they are put in a box. All boxes, Euclidian, geometrically smooth boxes.', 26);
insert into public.sentences (text, notebook_id) values ('Another definition of modernity: conversations can be more and more completely reconstructed with clips from other conversations taking place at the same time on the planet.', 26);
insert into public.sentences (text, notebook_id) values ('The twentieth century was the bankruptcy of the social utopia; the twentyfirst will be that of the technological one.', 26);
insert into public.sentences (text, notebook_id) values ('Efforts at building social, political, and medical utopias have caused nightmares; many cures and techniques came from martial efforts.', 26);
insert into public.sentences (text, notebook_id) values ('The Web''s "connectedness" creates a peculiar form of informational and pseudosocial promiscuity, which makes one feel clean after Web rationing.', 26);
insert into public.sentences (text, notebook_id) values ('In most debates, people seem to be trying to convince one another; but all they can hope for is new arguments to convince themselves.', 26);