INSERT INTO notebooks (name, name_zh) VALUES
('Preludes', '前言'),
('Counter Narratives', '反叙事'),
('Matters Ontological', '本体论问题'),
('The Sacred and the Profane', '神圣与世俗'),
('Chance, Success, Happiness, and Stoicism', '机遇、成功、幸福与斯多葛主义'),
('Charming and Less Charming Sucker Problems', '迷人或不那么迷人的“傻瓜问题”'),
('Theseus, or Living the Paleo Life', '忒修斯，或原始生活方式'),
('The Republic of Letters', '思想共和国'),
('The Universal and the Particular', '普遍与特殊'),
('Fooled by Randomness', '随机性的愚弄'),
('Aesthetics', '美学'),
('Ethics', '伦理学'),
('Robustness and Fragility', '稳健与脆弱'),
('The Ludic Fallacy and Domain Dependence', '游戏谬误与领域依赖'),
('Epistemology and Subtractive Knowledge', '认识论与“减法式知识”'),
('The Scandal of Prediction', '预测的丑闻'),
('Being a Philosopher and Managing to Remain One', '做一位哲学家并设法保持为哲学家'),
('Economic Life and Other Very Vulgar Subjects', '经济生活与其他极为庸俗的主题'),
('The Sage, the Weak, and the Magnificent', '智者、弱者与卓越者'),
('The Implicit and the Explicit', '隐性与显性'),
('On the Varieties of Love and Nonlove', '论爱与不爱的种种形式'),
('The End', '结尾');